src/accounts/controllers.py
from werkzeug.security import generate_password_hash

from flask import request, redirect, url_for, flash, render_template, Blueprint
from flask_login import login_user, login_required, logout_user, current_user

from accounts.services import find_by_username_and_password, create_user, edit_user, create_group
from accounts.forms import LoginForm, SignUpForm, EditUserInfoForm, CreateGroupForm
from products.services import get_paginated_product_user_list

from database import db

accounts_blueprint = Blueprint('accounts', __name__, template_folder='templates')


@accounts_blueprint.route('/signup', methods=('GET', 'POST'))
def signup():
    form = SignUpForm(request.form)

    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                create_user(form.email.data, form.username.data, form.password.data)
            except Exception as e:
                flash(str(e) or 'Unknown error', 'error')
                return redirect(url_for('accounts.signup'))
            else:
                return redirect(url_for('accounts.login'))

    return render_template('accounts/signup.html', form=form)


@accounts_blueprint.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user = find_by_username_and_password(form.username.data, form.password.data)
            except Exception as e:
                flash(str(e) or 'Unknown error')
                return redirect(url_for('accounts.login'))
            else:
                login_user(user, remember=form.remember.data)
                return redirect(url_for('accounts.dashboard'))
    return render_template('accounts/login.html', form=form)


@accounts_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('accounts.login'))


@accounts_blueprint.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    raw_page = request.args.get('page', '1')
    page = int(raw_page) if raw_page.isdigit() else 1
    pagination = get_paginated_product_user_list(page)
    return render_template('accounts/dashboard.html', pagination=pagination)


@accounts_blueprint.route("/statistics", methods=["GET"])
@login_required
def statistics():
    with db.engine.connect() as conn:
        results = conn.execute(db.text('''
            SELECT
                category,
                SUM(price) sum
            FROM product
            LEFT JOIN user_product up on product.id = up.product_id
            LEFT JOIN "user" u on up.user_id = u.id
            WHERE u.id = (:i)
            GROUP BY category;
        '''), [{"i": current_user.id}])
    return render_template('accounts/statistics.html', results=results)


@accounts_blueprint.route('/profile', methods=('GET', 'POST'))
@login_required
def profile():
    form = EditUserInfoForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                current_email = current_user.email
                new_email = form.email.data if form.email.data else current_email
                new_name = form.username.data if form.username.data else current_user.name
                new_password = generate_password_hash(form.password.data) if form.password.data else None
                edit_user(current_email, new_email, new_name, new_password)
            except Exception as e:
                flash(str(e) or 'Unknown error', 'error')
                return redirect(url_for('accounts.profile'))
            else:
                return redirect(url_for('accounts.dashboard'))

    return render_template('accounts/profile.html', form=form, user=current_user)


@accounts_blueprint.route("/groups", methods=["GET"])
@login_required
def groups():
    return render_template('accounts/groups.html')


@accounts_blueprint.route("/create_group", methods=('GET', 'POST'))
@login_required
def create_group_page():
    form = CreateGroupForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                create_group(form.name.data, form.party.data.split())
            except Exception as e:
                flash(str(e) or 'Unknown error', 'error')
                return redirect(url_for('accounts.create_group'))
            else:
                return redirect(url_for('accounts.groups'))
    return render_template('accounts/create_group.html', form=form)

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}">

    <title>{% block title %}{% endblock %} - Fuck</title>
</head>

<body>
    {% if current_user.name %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url_for('accounts.dashboard') }}">
                    <img src="{{ url_for('static', filename='icons/logo.svg') }}" alt="" width="80" height="45">
                </a>
                <div class="navbar" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link fs-5" aria-current="page" href="{{ url_for('accounts.groups') }}">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-5" href="{{ url_for('accounts.statistics') }}">Statistics</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-5 fw-bolder" href="{{ url_for('accounts.profile') }}"> {{ current_user.name }} </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-5 fw-lighter" href="{{ url_for('accounts.logout') }}">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% else %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="{{ url_for('static', filename='icons/logo.svg') }}" alt="" width="80" height="45">
                </a>
                <div class="navbar" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link fs-5 fw-lighter" href="{{ url_for('accounts.login') }}">LogIn</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fs-5 fw-lighter" href="{{ url_for('accounts.signup') }}">SignUp</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% endif %}

    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>

src/templates/macros.html
{% macro render_pagination(pagination, endpoint) %}
    <div class=pagination>
        {%- for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <a class="pagination_link" href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
                {% else %}
                    <strong>{{ page }}</strong>
                {% endif %}
            {% else %}
                <span class=ellipsis>…</span>
            {% endif %}
        {%- endfor %}
    </div>
{% endmacro %}