src/accounts/models.py
from flask_login import UserMixin

from database import db

UserGroup = db.Table(
    'user_group',
    db.Column('id', db.Integer, primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('group_id', db.Integer, db.ForeignKey('group.id'))
)


class User(db.Model, UserMixin):
    __tablename__ = "user"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), nullable=False)
    email = db.Column(db.String(128), unique=True)
    hashed_password = db.Column(db.String(1024), nullable=False)
    users_products = db.relationship("UserProduct", back_populates="users")
    groups = db.relationship('Group', secondary=UserGroup, backref='User')

    def __repr__(self):
        return f"<User {self.name}, id {self.id}>"


class Group(db.Model):
    __tablename__ = "group"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    users = db.relationship('User', secondary=UserGroup, backref='Group')
    products = db.relationship("GroupProduct", back_populates="groups")

    def __repr__(self):
        return f"<Group {self.name}>"


class UserProduct(db.Model):
    __tablename__ = "user_product"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    users = db.relationship("User", back_populates="users_products")
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'))
    products = db.relationship("Product", back_populates="users_products")


class GroupProduct(db.Model):
    __tablename__ = "group_product"

    id = db.Column(db.Integer, primary_key=True)
    group_id = db.Column(db.Integer, db.ForeignKey('group.id'))
    groups = db.relationship("Group", back_populates="products")
    product_id = db.Column(db.Integer, db.ForeignKey('product.id'))
    products = db.relationship("Product", back_populates="groups_products")

src/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, Optional


class LoginForm(FlaskForm):
    username = StringField(
        "username",
        validators=[
            DataRequired(),
            Length(min=4, max=32)
        ]
    )
    password = PasswordField(
        "password",
        validators=[
            DataRequired(),
            Length(min=6, max=64)
        ]
    )
    remember = BooleanField("remember")


class SignUpForm(FlaskForm):
    email = StringField(
        "email",
        validators=[
            DataRequired(),
            Email(),
            Length(min=6)
        ]
    )
    username = StringField(
        "username",
        validators=[
            DataRequired(),
            Length(min=4, max=32)
        ]
    )
    password = PasswordField(
        "password",
        validators=[
            DataRequired(),
            Length(min=6, max=64),
            EqualTo(fieldname='confirm_password')
        ]
    )
    confirm_password = PasswordField(
        "confirm_password",
        validators=[
            DataRequired(),
            Length(min=6, max=64),
        ]
    )


class EditUserInfoForm(FlaskForm):
    email = StringField(
        "email",
        validators=[
            Optional(),
            Email(),
            Length(min=6)
        ]
    )
    username = StringField(
        "username",
        validators=[
            Optional(),
            Length(min=4, max=32)
        ]
    )
    password = PasswordField(
        "password",
        validators=[
            Optional(),
            Length(min=6, max=64),
            EqualTo(fieldname='confirm_password')
        ]
    )
    confirm_password = PasswordField(
        "confirm_password",
        validators=[
            Optional(),
            Length(min=6, max=64),
        ]
    )


class CreateGroupForm(FlaskForm):
    name = StringField(
        "name",
        validators=[
            DataRequired(),
            Length(min=4, max=32)
        ]
    )
    party = TextAreaField(
        "party",
        validators=[
            Optional()
        ]
    )

src/accounts/controllers.py
from werkzeug.security import generate_password_hash

from flask import request, redirect, url_for, flash, render_template, Blueprint
from flask_login import login_user, login_required, logout_user, current_user

from accounts.services import find_by_username_and_password, create_user, edit_user, create_group
from accounts.forms import LoginForm, SignUpForm, EditUserInfoForm, CreateGroupForm
from products.services import get_paginated_product_user_list

from database import db

accounts_blueprint = Blueprint('accounts', __name__, template_folder='templates')


@accounts_blueprint.route('/signup', methods=('GET', 'POST'))
def signup():
    form = SignUpForm(request.form)

    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                create_user(form.email.data, form.username.data, form.password.data)
            except Exception as e:
                flash(str(e) or 'Unknown error', 'error')
                return redirect(url_for('accounts.signup'))
            else:
                return redirect(url_for('accounts.login'))

    return render_template('accounts/signup.html', form=form)


@accounts_blueprint.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                user = find_by_username_and_password(form.username.data, form.password.data)
            except Exception as e:
                flash(str(e) or 'Unknown error')
                return redirect(url_for('accounts.login'))
            else:
                login_user(user, remember=form.remember.data)
                return redirect(url_for('accounts.dashboard'))
    return render_template('accounts/login.html', form=form)


@accounts_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('accounts.login'))


@accounts_blueprint.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    raw_page = request.args.get('page', '1')
    page = int(raw_page) if raw_page.isdigit() else 1
    pagination = get_paginated_product_user_list(page)
    return render_template('accounts/dashboard.html', pagination=pagination)


@accounts_blueprint.route("/statistics", methods=["GET"])
@login_required
def statistics():
    with db.engine.connect() as conn:
        results = conn.execute(db.text('''
            SELECT
                category,
                SUM(price) sum
            FROM product
            LEFT JOIN user_product up on product.id = up.product_id
            LEFT JOIN "user" u on up.user_id = u.id
            WHERE u.id = (:i)
            GROUP BY category;
        '''), [{"i": current_user.id}])
    return render_template('accounts/statistics.html', results=results)


@accounts_blueprint.route('/profile', methods=('GET', 'POST'))
@login_required
def profile():
    form = EditUserInfoForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                current_email = current_user.email
                new_email = form.email.data if form.email.data else current_email
                new_name = form.username.data if form.username.data else current_user.name
                new_password = generate_password_hash(form.password.data) if form.password.data else None
                edit_user(current_email, new_email, new_name, new_password)
            except Exception as e:
                flash(str(e) or 'Unknown error', 'error')
                return redirect(url_for('accounts.profile'))
            else:
                return redirect(url_for('accounts.dashboard'))

    return render_template('accounts/profile.html', form=form, user=current_user)


@accounts_blueprint.route("/groups", methods=["GET"])
@login_required
def groups():
    return render_template('accounts/groups.html')


@accounts_blueprint.route("/create_group", methods=('GET', 'POST'))
@login_required
def create_group_page():
    form = CreateGroupForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                create_group(form.name.data, form.party.data.split())
            except Exception as e:
                flash(str(e) or 'Unknown error', 'error')
                return redirect(url_for('accounts.create_group'))
            else:
                return redirect(url_for('accounts.groups'))
    return render_template('accounts/create_group.html', form=form)

src/accounts/templates/accounts/create_group.html
{% extends 'base.html' %}

{% block title %}Create Group{% endblock %}

{% block content %}
<section class="container">
    <div class="row">
        <section class="form-border">

            <form method="post" id="form-form">
                {{ form.csrf_token }}

                <div class="col-sm-10 offset-sm-1">
                    <input class="form-control" name="name" id="name" placeholder="Name" value="{{ form.name.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <textarea class="form-control" name="party" id="party" placeholder="Party" value="{{ form.party.data }}"></textarea>
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="submit" class="btn form-control" value="Add">
                </div>
            </form>
        </section>
    </div>
</section>
{% endblock %}

src/accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% from 'macros.html' import render_pagination with context %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="container">
        <div class="row dashboard">
            <div class="col-10">
                <div class="row">
                    <div class="col-4">
                        <input type="text" class="form-control" name="search_product_name" id="search_product_name" placeholder="Name">
                    </div>
                    <div class="col-4">
                        <input type="text" class="form-control" name="search_product_category" id="search_product_category" placeholder="Category">
                    </div>
                    <div class="col-1">
                        <input type="text" class="form-control" name="search_product_from" id="search_product_from" placeholder="From">
                    </div>
                    <div class="col-1">
                        <input type="text" class="form-control" name="search_product_to" id="search_product_to" placeholder="To">
                    </div>
                    <div class="col-2">
                        <input type="submit" class="form-control search_btn" value="Search">
                    </div>
                </div>
            </div>

            <div class="col-2">
                <form action="{{ url_for('products.create_product_for_user_page') }}">
                    <input type="submit" class="form-control dashboard_btn" value="Add">
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row align-items-start row-cols-4">
            {% for product in pagination.items %}
                <div class="col dashboard_card">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title fw-bold fs-2">{{ product.price }}$</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ product.category }}</h6>
                            <p class="card-text">{{ product.name }}</p>
                            <input type="submit" class="btn in_card" value="Edit">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="container">
        <div class="col-12">
            {{ render_pagination(pagination=pagination, endpoint='accounts.dashboard') }}
        </div>
    </div>
    <script src="/src/static/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
{% endblock %}

src/accounts/templates/accounts/groups.html
{% extends 'base.html' %}
{#{% from 'macros.html' import render_pagination with context %}#}

{% block title %}Statistic{% endblock %}

{% block content %}
    <div class="container">
        <div class="row dashboard">
            <div class="col-10">
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-4"></div>
                    <div class="col-1"></div>
                    <div class="col-1"></div>
                    <div class="col-2"></div>
                </div>
            </div>

            <div class="col-2">
                <form action="{{ url_for('accounts.create_group_page') }}">
                    <input type="submit" class="form-control dashboard_btn" value="Add">
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row align-items-start row-cols-2">
            <h5 class="fw-bold fs-2">Не работает(((</h5>
        </div>
    </div>

    <div class="container">
        <div class="row align-items-start row-cols-2">
            {% for res in results %}
                <div class="col dashboard_card">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title fw-bold fs-2">{{ res.name }}</h5>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{#    <div class="container">#}
{#        <div class="col-12">#}
{#            {{ render_pagination(pagination=pagination, endpoint='accounts.dashboard') }}#}
{#        </div>#}
{#    </div>#}
    <script src="/src/static/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<section class="container">
    <div class="row">
        <section class="form-border">

            <form method="post" id="form-form">
                {{ form.csrf_token }}

                <div class="col-sm-10 offset-sm-1">
                    <input type="text" class="form-control" name="username" id="username" placeholder="Name" value="{{ form.username.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password" value="{{ form.password.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input class="form-check-input" type="checkbox" name="remember" id="flexCheckDefault" value="{{ form.remember.data }}">
                    <label class="form-check-label" for="flexCheckDefault">
                        Remember me
                    </label>
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="submit" class="btn form-control" value="Login">
                </div>
            </form>
        </section>
    </div>
</section>
{% endblock %}

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}SignUp{% endblock %}

{% block content %}
<section class="container">
    <div class="row">
        <section class="form-border">

            <form method="post" id="form-form">
                {{ form.csrf_token }}

                <div class="col-sm-10 offset-sm-1">
                    <input type="email" class="form-control" name="email" id="email" placeholder="{{ user.email }}" value="{{ form.email.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="text" class="form-control" name="username" id="username" placeholder="{{ user.name }}" value="{{ form.username.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password" value="{{ form.password.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="Confirm Password" value="{{ form.confirm_password.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="submit" class="btn form-control" value="Edit">
                </div>
            </form>
        </section>
    </div>
</section>
{% endblock %}

src/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}SignUp{% endblock %}

{% block content %}
<section class="container">
    <div class="row">
        <section class="form-border">

            <form method="post" id="form-form">
                {{ form.csrf_token }}

                <div class="col-sm-10 offset-sm-1">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Email" value="{{ form.email.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="text" class="form-control" name="username" id="username" placeholder="Name" value="{{ form.username.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password" value="{{ form.password.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="Confirm Password" value="{{ form.confirm_password.data }}">
                </div>

                <div class="col-sm-10 offset-sm-1">
                    <input type="submit" class="btn form-control" value="SignUp">
                </div>
            </form>
        </section>
    </div>
</section>
{% endblock %}

src/accounts/templates/accounts/statistics.html
{% extends 'base.html' %}
{#{% from 'macros.html' import render_pagination with context %}#}

{% block title %}Statistic{% endblock %}

{% block content %}
    <div class="container">
        <div class="row align-items-start row-cols-2">
            {% for res in results %}
                <div class="col dashboard_card">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title fw-bold fs-2">{{ res.sum }}$</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ res.category }}</h6>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{#    <div class="container">#}
{#        <div class="col-12">#}
{#            {{ render_pagination(pagination=pagination, endpoint='accounts.dashboard') }}#}
{#        </div>#}
{#    </div>#}
    <script src="/src/static/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
{% endblock %}